from .lib_sf import CorpusEntry, TestableEntry


class Generation:
    def into_members(self) -> list[TestableEntry]: ...


class MABConfig:
    # threshhold for syntax penalty
    exploration_constant: float
    max_accepted_syntax_err: float
    # accepted + cov_inc should be 1. ideally
    weight_accepted: float
    weight_cov_inc: float
    # sum(malus) shopuld be 1. ideallyu
    weight_timeout: float
    weight_syntax_penalty: float
    weight_size_penalty: float
    weight_time_penalty: float
    # baseline size
    scale_size: float

    @staticmethod
    def new_default() -> MABConfig: ...


class MABBody:
    def __init__(self) -> None: ...
    def with_config(self, config: MABConfig) -> None: ...


class CorpusMinimizerBuilder:
    @staticmethod
    def greedy_coverage(max_edges: int) -> CorpusMinimizerBuilder: ...


class CorpusManagerBuilder:
    @staticmethod
    def dynamic_cache(disk_cache: DiskCacheBuilder) -> CorpusManagerBuilder: ...
    @staticmethod
    def in_memory() -> CorpusManagerBuilder: ...


class DiskCacheBuilder:
    @staticmethod
    def sharded(cache_dir: str) -> DiskCacheBuilder: ...
    @staticmethod
    def blob(cache_dir: str) -> DiskCacheBuilder: ...
    @staticmethod
    def sql_saver(backend: DiskCacheBuilder, save_dir: str) -> DiskCacheBuilder: ...


class SchedulerBuilder:
    @staticmethod
    def weighted_random() -> SchedulerBuilder: ...
    @staticmethod
    def adaptive_weighted_random() -> SchedulerBuilder: ...
    @staticmethod
    def ucb1(body: MABBody) -> SchedulerBuilder: ...
    @staticmethod
    def weighted_ucb1(body: MABBody) -> SchedulerBuilder: ...
    @staticmethod
    def batched(scheduler: SchedulerBuilder) -> SchedulerBuilder: ...
    @staticmethod
    def fast_weigthed_ucb1(body: MABBody) -> SchedulerBuilder: ...


class StrategyBuilder:
    @staticmethod
    def random_sampler(
        min_choices: int, max_choixes: int, choices: list[StrategyBuilder]
    ) -> StrategyBuilder: ...
    @staticmethod
    def randomize(strategy: StrategyBuilder, probability: float) -> StrategyBuilder: ...
    @staticmethod
    def splice_in(p_extend: float = 0.5) -> StrategyBuilder: ...
    @staticmethod
    def splice_out(p_extend: float = 0.5) -> StrategyBuilder: ...
    @staticmethod
    def table_guard() -> StrategyBuilder: ...
    @staticmethod
    def op_flip(flip_chance: float = 0.3) -> StrategyBuilder: ...
    @staticmethod
    def num_bounds(mutate_chance: float = 0.3) -> StrategyBuilder: ...
    @staticmethod
    def null_inject(mutation_chande: float = 0.3) -> StrategyBuilder: ...
    @staticmethod
    def set_ops() -> StrategyBuilder: ...
    @staticmethod
    def type_cast(mutation_chance: float = 0.3) -> StrategyBuilder: ...
    @staticmethod
    def sub_query(mutation_chande: float = 0.3) -> StrategyBuilder: ...
    @staticmethod
    def expr_shuffle(mutation_chance: float = 0.3) -> StrategyBuilder: ...
    @staticmethod
    def relation_shuffle(mutation_chance: float = 0.3) -> StrategyBuilder: ...
    @staticmethod
    def scheduled(strategy: StrategyBuilder, body: MABBody) -> StrategyBuilder: ...
    @staticmethod
    def tree_mutate_stmt(
        operator: TreeMutatorOperation, chance_per_node: float = 0.3, chance_per_field: float = 0.1
    ) -> StrategyBuilder: ...
    @staticmethod
    def tree_mutate_expr(
        operator: TreeMutatorOperation, chance_per_node: float = 0.3, chance_per_field: float = 0.1
    ) -> StrategyBuilder: ...
    @staticmethod
    def table_name_guard() -> StrategyBuilder: ...
    @staticmethod
    def recursive_expand_expr(
        max_depth: int = 3, chance_per_node: float = 0.1, chance_per_level: float = 0.5
    ) -> StrategyBuilder: ...
    @staticmethod
    def hoist_expr(chance_per_node: float = 0.1) -> StrategyBuilder: ...
    @staticmethod
    def ucb1(
        body: MABBody, strategies: list[StrategyBuilder], choose: int = 1
    ) -> StrategyBuilder: ...
    @staticmethod
    def arbitrary_stmt_generator() -> StrategyBuilder: ...
    @staticmethod
    def arbitrary_expr_generator() -> StrategyBuilder: ...
    @staticmethod
    def repeat(rule: StrategyBuilder, up_to: int) -> StrategyBuilder: ...
    @staticmethod
    def noop() -> StrategyBuilder: ...
    @staticmethod
    def force_ident() -> StrategyBuilder: ...


class TreeMutatorOperation:
    @staticmethod
    def shuffle_two() -> TreeMutatorOperation: ...
    @staticmethod
    def shuffle_self() -> TreeMutatorOperation: ...
    @staticmethod
    def null_random() -> TreeMutatorOperation: ...


class SeedGeneratorBuilder:
    @staticmethod
    def literal(lit: str) -> SeedGeneratorBuilder: ...
    @staticmethod
    def dir_reader(dir: str) -> SeedGeneratorBuilder: ...


class Engine:
    def __init__(
        self,
        scheduler: SchedulerBuilder,
        corpus_handler: CorpusManagerBuilder,
        corpus_minimzer: CorpusMinimizerBuilder,
        strategies: list[StrategyBuilder],
        shmem_queue: IPCTokenQueue,
        mab_bodies: list[MABBody] = [],
        rng_seed: int = 42,
    ) -> None: ...
    def populate(self, seed_builders: list[SeedGeneratorBuilder]) -> None: ...
    def mutate_batch(self, batch_size: int) -> Generation: ...
    def commit_test_result(self, entry: TestableEntry, result: TestResult) -> None: ...
    def snapshot(self) -> list[CorpusEntry]: ...
    def clear_strategies(self) -> None: ...
    def add_strategy(self, strategy: StrategyBuilder) -> None: ...
    def chore(self) -> None: ...
    def return_token(self, token: IPCTokenHandle) -> None: ...
    def corpus_size(self) -> int: ...
    def clear(self) -> None: ...


class IPCTokenQueue:
    def __init__(self, n_workers: int, max_edge: int) -> None: ...
    async def recv(self) -> IPCTokenHandle | None: ...
    def send(self, token: IPCTokenHandle) -> None: ...


class IPCTokenHandle:
    def as_env(self) -> str: ...
    def id(self) -> int: ...


class TestResult:
    triggers_bug: bool
    is_valid_syntax: bool
    exec_time: int
    query_size: int
    token: IPCTokenHandle

    def __init__(
        self,
        exec_time: int,
        query_size: int,
        token: IPCTokenHandle,
        is_valid_syntax: bool = True,
        triggers_bug: bool = False,
    ) -> None: ...
