#! /bin/bash

cd /app

time setarch -R $(uname -m) just run-docker_ --seeds /app/seeds --save_to docker_out/queries --stop_at 10000 --keyword_coverage_to docker_out/keyword_coverage --keyword_coverage_report_every 100
