#! /bin/bash

cd /app

rm -rf docker_out/queries docker_out/keyword_coverage
mkdir -p docker_out

time setarch -R $(uname -m) just run-docker_ --seeds /app/seeds --save_to docker_out/queries --stop_at 10000 --eval_requirement true
uv run python -m tester.keyword_coverage docker_out/queries --out docker_out/keyword_coverage
uv run python -m tester.keyword_average_frequency docker_out/queries --out docker_out/keyword_coverage
